### ISSUE TITLE
tqdm error while flashing

### ISSUE THREAD

**Issue by akeonly** [grigorig/stcgal#41]
I found below error while trying to flash with this command
"python3 stcgal.py -D  Hello.hex -b 9600"

> Traceback (most recent call last):
  File "/usr/local/bin/stcgal", line 11, in <module>
    load_entry_point('stcgal==1.4', 'console_scripts', 'stcgal')()
  File "/usr/local/lib/python3.6/dist-packages/stcgal-1.4-py3.6.egg/stcgal/frontend.py", line 230, in cli
  File "/usr/local/lib/python3.6/dist-packages/stcgal-1.4-py3.6.egg/stcgal/frontend.py", line 180, in run
  File "/usr/local/lib/python3.6/dist-packages/stcgal-1.4-py3.6.egg/stcgal/frontend.py", line 139, in program_mcu
  File "/usr/local/lib/python3.6/dist-packages/stcgal-1.4-py3.6.egg/stcgal/protocols.py", line 972, in program_flash
  File "/usr/local/lib/python3.6/dist-packages/stcgal-1.4-py3.6.egg/stcgal/protocols.py", line 100, in progress_bar_cb
AttributeError: type object 'tqdm' has no attribute 'tqdm'

**Comment by nekromant** [comment]
I think there must be a problem with your tqdm installation. Try installing a recent tqdm via pip

**Comment by akeonly** [comment]
I can use it from python3 console

```
rambo:~$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tqdm import tqdm;
>>> for i in tqdm(range(100000)):
...   pass
... 
100%|██████████████████████████████| 100000/100000 [00:00<00:00, 2382639.91it/s]
>>> exit()
rambo:~$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tqdm;
>>> from i in tqdm(range(10000)):
  File "<stdin>", line 1
    from i in tqdm(range(10000)):
            ^
SyntaxError: invalid syntax
```

and when I update 2 lines to below it works.
protocol.py:40
`from tqdm import tqdm`
protocol.py:100
`self.progress = tqdm(`

**Comment by akeonly** [comment]
This is how I install tqdm
```
rambo:Hello$ pip3 install tqdm
Collecting tqdm
  Using cached https://files.pythonhosted.org/packages/93/24/6ab1df969db228aed36a648a8959d1027099ce45fad67532b9673d533318/tqdm-4.23.4-py2.py3-none-any.whl
Installing collected packages: tqdm
Successfully installed tqdm-4.23.4
```

**Comment by grigorig** [comment]
I can't reproduce this problem, this is very odd. Can you provide more details about your environment?
